server:
  port: 8080

spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      
  datasource:
    url: jdbc:mysql://localhost:3306/homework_system?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Moretti0304
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: your-secret-key-here-should-be-very-long-and-secure-please-change-in-production
  expiration: 86400000 # 24 hours

file:
  upload-dir: ./uploads 